package com.baosight.iwater.system.user.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.baosight.iwater.system.user.pojo.SystemUser;

@Repository
public interface SystemUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    int insert(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    int insertSelective(SystemUser record);
    
    List<SystemUser> queryList(SystemUser record);
}