package com.baosight.iwater.system.user.pojo;

public class SystemUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.user_id
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.user_name
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.pass_word
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.china_name
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String chinaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.email
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.phone_number
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.tel
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.address
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.dept
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.user_desc
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String userDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.status
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.role
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.user_id
     *
     * @return the value of b_user.user_id
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.user_id
     *
     * @param userId the value for b_user.user_id
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.user_name
     *
     * @return the value of b_user.user_name
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.user_name
     *
     * @param userName the value for b_user.user_name
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.pass_word
     *
     * @return the value of b_user.pass_word
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.pass_word
     *
     * @param passWord the value for b_user.pass_word
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.china_name
     *
     * @return the value of b_user.china_name
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getChinaName() {
        return chinaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.china_name
     *
     * @param chinaName the value for b_user.china_name
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setChinaName(String chinaName) {
        this.chinaName = chinaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.email
     *
     * @return the value of b_user.email
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.email
     *
     * @param email the value for b_user.email
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.phone_number
     *
     * @return the value of b_user.phone_number
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.phone_number
     *
     * @param phoneNumber the value for b_user.phone_number
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.tel
     *
     * @return the value of b_user.tel
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.tel
     *
     * @param tel the value for b_user.tel
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.address
     *
     * @return the value of b_user.address
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.address
     *
     * @param address the value for b_user.address
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.dept
     *
     * @return the value of b_user.dept
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.dept
     *
     * @param dept the value for b_user.dept
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.user_desc
     *
     * @return the value of b_user.user_desc
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.user_desc
     *
     * @param userDesc the value for b_user.user_desc
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.status
     *
     * @return the value of b_user.status
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.status
     *
     * @param status the value for b_user.status
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.role
     *
     * @return the value of b_user.role
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.role
     *
     * @param role the value for b_user.role
     *
     * @mbg.generated Wed Dec 28 17:07:28 GMT+08:00 2016
     */
    public void setRole(String role) {
        this.role = role;
    }
}